# Generated by Django 3.2.6 on 2021-09-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverage',
            name='dish',
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.recipe')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.beverage')),
            ],
            options={
                'ordering': ['dish'],
            },
        ),
    ]
