# Generated by Django 3.2.6 on 2021-09-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20210908_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairing',
            name='dish',
            field=models.CharField(max_length=200),
        ),
    ]
