# Generated by Django 3.2.6 on 2021-09-20 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_pairing_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage_allegrents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.beverage')),
            ],
        ),
    ]
