# Generated by Django 3.2.6 on 2021-09-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_beverage_allegrents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beverage_allegrents',
        ),
    ]
