# Generated by Django 3.2.6 on 2021-09-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_delete_beverage_allegrents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage_allergets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.beverage')),
            ],
        ),
    ]
