# Generated by Django 3.2.6 on 2021-09-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_beverage_allergets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage_allergets',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
