# Generated by Django 3.2.6 on 2021-09-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_alter_beverage_allergets_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['title_dish']},
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='title',
            new_name='title_dish',
        ),
    ]
