# Generated by Django 3.2.6 on 2021-09-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_auto_20210927_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='selector',
            field=models.CharField(choices=[('Main', 'Main'), ('Starter', 'Starter'), ('Dessert', 'Dessert'), ('Breakfast', 'Breakfast'), ('DDRbreaks', 'DDRbreaks')], max_length=50),
        ),
    ]
